### PR TITLE
Resolve strict mode UntaggedSocketViolation issue

### LINKED ISSUE #357: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected
When run test app on phone, it will keep show error logs and freeze, then crash.
```
2019-03-11 12:36:21.967 18807-18876/com.mapbox.android.events.testapp D/StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2023)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:50)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:313)
        at libcore.io.IoBridge.socket(IoBridge.java:640)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:124)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
        at java.net.Socket.createImpl(Socket.java:489)
        at java.net.Socket.getImpl(Socket.java:552)
        at java.net.Socket.setSoTimeout(Socket.java:1180)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.mapbox.android.telemetry.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:28)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

```

Solution:
Add call `TrafficStats.setThreadStatsTag(THREAD_ID);` in `com.mapbox.android.telemetry.GzipRequestInterceptor.intercept`

### PR DESCRIPTION
**Pull request by Chaoba**
Resolves #357 

There is a strict mode issue while running test app

```
StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2023)
```
Root cause

Solution:
Add call TrafficStats.setThreadStatsTag(THREAD_ID); in `com.mapbox.android.telemetry.GzipRequestInterceptor.intercept`

### CODE REVIEW

File: libtelemetry/src/main/java/com/mapbox/android/telemetry/GzipRequestInterceptor.java [hunk 1]
```diff
@@ -13,14 +15,16 @@
...
 
   @Override
   public Response intercept(Interceptor.Chain chain) throws IOException {
     Request originalRequest = chain.request();
     if (originalRequest.body() == null || originalRequest.header("Content-Encoding") != null) {
       return chain.proceed(originalRequest);
     }
-
+    //Fix strict mode issue, see https://github.com/square/okhttp/issues/3537#issuecomment-431632176
+    TrafficStats.setThreadStatsTag(THREAD_ID);
```
Comment (andrlee) [inline libtelemetry/src/main/java/com/mapbox/android/telemetry/GzipRequestInterceptor.java]: I'm a bit confused why this has to be part of the interceptor logic? Another consideration do we really have to do this for all builds? Since this is a workaround to silence `StrictMode` should we do this just for debug builds? Also should we do `TrafficStats #clearThreadStatsTag` what will happen if we don't do this?

Comment (Chaoba) [reply libtelemetry/src/main/java/com/mapbox/android/telemetry/GzipRequestInterceptor.java]: This must be done in the request thread, this method is in the request thread. Let's put it only in debug mode. Whether we set or clear tag will not provide additional value except for silencing Strict mode waring.

Comment (andrlee) [reply libtelemetry/src/main/java/com/mapbox/android/telemetry/GzipRequestInterceptor.java]: @Chaoba let's tag only on `debug` builds and also on api levels above X.

Comment (Chaoba) [reply libtelemetry/src/main/java/com/mapbox/android/telemetry/GzipRequestInterceptor.java]: You mean 2.2X api level 8? If so we don't need to worry about it since the minSdkVersion of telemetry is 14 which is right the version that this method is added.
