### PR TITLE
[telemetry] Workaround for `MapboxTelemetryService` crash.

### LINKED ISSUE #530: 🐞 Crash in background for Android 11
**Context**
The issue is reported in https://github.com/mapbox/mapbox-search-android-examples/issues/25 and, according to crash logs, there might be something with `mapbox-android-telemetry`.

**Configuration**
 - SDK Version: v7.0.0
 - Android OS Version: Android 11
 - App: External app with Search SDK integration

**Steps to Reproduce**
There are no defined steps, but according to the customer:

> I have tried many many things but I cant reproduce the issue. I have noticed that app crashes 98% when it is in background. (ie. activity is not initialized)

**Expected**
Application doesn't crash in background.

**Logging**
Crash stacktrace:
```
Fatal Exception: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.mapbox.android.telemetry.MapboxTelemetryService$Binder
    at com.mapbox.android.telemetry.provider.MapboxTelemetryInitProvider$1.onServiceConnected(MapboxTelemetryInitProvider.java:38)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2084)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2116)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8506)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### PR DESCRIPTION
**Pull request by tarigo**
Resolves #530.

Workaround for the crash that can happen in multiple processes of WorkManager. The service functionality is tracking the lifecycle of the app's activity, so in case of background tasks, we can safely ignore this error.

### CODE REVIEW

File: libtelemetry/src/full/java/com/mapbox/android/telemetry/provider/MapboxTelemetryInitProvider.java [hunk 1]
```diff
@@ -35,8 +35,12 @@
   private final ServiceConnection telemetryServiceConnection = new ServiceConnection() {
     @Override
     public void onServiceConnected(ComponentName name, IBinder service) {
-      MapboxTelemetryService.Binder binder = (MapboxTelemetryService.Binder) service;
-      telemetryService = binder.getService();
+      if (service instanceof MapboxTelemetryService.Binder) {
+        MapboxTelemetryService.Binder binder = (MapboxTelemetryService.Binder) service;
+        telemetryService = binder.getService();
+      } else {
+        Log.e(TAG, "Invalid type of MapboxTelemetryService.Binder=" + service);
```
Comment (mr1sunshine) [inline libtelemetry/src/full/java/com/mapbox/android/telemetry/provider/MapboxTelemetryInitProvider.java:42]: do we want to have it as an `error` or maybe enough to have it as a `warning`?

**Review by mr1sunshine — APPROVED** [review]
LGTM, with a question about log type.

File: libtelemetry/src/full/java/com/mapbox/android/telemetry/provider/MapboxTelemetryInitProvider.java (hunk 1 above)
Comment (tarigo) [reply libtelemetry/src/full/java/com/mapbox/android/telemetry/provider/MapboxTelemetryInitProvider.java]: Yes, fixed.
