### PR TITLE
[telemetry]  Android 12 compartibility fixes.

### LINKED ISSUE #532: 🐞 Android 12: PendingIntent mutability
When targeting Android 12 as target SDK and including `mapbox-events-android`. We are hitting an IllegalArgumentException, this is because pending intents are now required to be tagged as mutable/immutable. For more information see [pending-intent-immutability](https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability). 

Pending intents are used in the AlarmSchedulerFlusher:
https://github.com/mapbox/mapbox-events-android/blob/d73ca293b194376516997b73c5139b28430be671/libtelemetry/src/full/java/com/mapbox/android/telemetry/AlarmSchedulerFlusher.java#L20

While Android 12 is to be expected to be released by September, we need to incorporate these fixes in downstream projects. 

cc @tarigo @mapbox/core-sdk

### PR DESCRIPTION
**Pull request by tarigo**
Fixes #532.

### CODE REVIEW

**Review by tobrun — APPROVED** [review]
:shipit:

File: libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationEngineControllerImpl.java [hunk 1]
```diff
@@ -85,7 +87,11 @@ private void removeLocationUpdates() {
   private PendingIntent getPendingIntent() {
     // Implicit intent is required here to work with registering receiver via context
     Intent intent = new Intent(LocationUpdatesBroadcastReceiver.ACTION_LOCATION_UPDATED);
-    return PendingIntent.getBroadcast(applicationContext, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
+    int flags = PendingIntent.FLAG_UPDATE_CURRENT;
+    if (BuildCompat.isAtLeastS()) {
+      flags |= 33554432; //TODO: replace with PendingIntent.FLAG_MUTABLE after Android 12 release
```
Comment (Guardiola31337) [inline libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationEngineControllerImpl.java:92]: @tarigo Should we cut a ticket so we don't forget? BTW Android 12 is officially released 🎉

**Comment by wangyijenny** [comment]
I'm updating an app that used a very old version of mapbox. Do you know what the earliest version of Mapbox that would work with Android 12 is?
